'use strict'
const cl = require('./azureStorage')
const Promise = require('bluebird')
const log = require('./server/init/logging')
// const mkdir = Promise.promisify(require('fs').mkdir)

function _test (path, path1) {
  return cl.cloudCreateContainer('test')
.then(() => log.info('\nlisting files in container test'))
.then(() => cl.cloudListFile('test'))
.then(() => log.info('\n (1) Passed........\n'))
.then(() => log.info('\ncreating 6 files in Azure'))
.then(() => cl.cloudStoreTextToFile('enrollments.STUDENTS.DM1578VT152.1480494800005.csv', 'test', 'Hej på dig ole'))
.then(() => cl.cloudStoreTextToFile('enrollments.STUDENTS.DM1578VT152.1480494800006.csv', 'test', 'Hej på dig dole'))
.then(() => cl.cloudStoreTextToFile('enrollments.STUDENTS.DM1578VT152.1480494800007.csv', 'test', 'Hej på dig dof'))
.then(() => cl.cloudStoreTextToFile('enrollments.STUDENTS.DM1578VT152.1480494800008.csv', 'test', 'Hej på dig Kinke'))
.then(() => cl.cloudStoreTextToFile('enrollments.STUDENTS.DM1578VT152.1480494800009.csv', 'test', 'Hej på dig lane'))
.then(() => cl.cloudStoreTextToFile('enrollments.STUDENTS.DM1578VT152.1480494800010.csv', 'test', 'Hej på dig koff'))
.then(() => log.info('\n (2) Passed........\n'))
.then(() => log.info('\nlisting files in conainer test again'))
.then(() => cl.cloudListFile('test'))
.then(() => log.info('\n (3) Passed........\n'))
.then(() => log.info('\nTesting missing argument list in _storeTexttoFileAzure'))
.then(() => cl.cloudStoreTextToFile('', 'test', 'Hej på dig ole'))
.catch(error => log.info('In Error: ', error))
.then(() => cl.cloudStoreTextToFile('enrollments.STUDENTS.DM1578VT152.1480494800011.csv', '', 'Hej på dig dole'))
.catch(error => log.info('In Error: ', error))
.then(() => log.info('\n (4) Passed........\n'))
.then(() => log.info('\nRetriving 6 files from Azure to CSV catalog'))
.then(() => cl.cloudgetFile('enrollments.STUDENTS.DM1578VT152.1480494800005.csv', 'test', path))
.then(() => cl.cloudgetFile('enrollments.STUDENTS.DM1578VT152.1480494800006.csv', 'test', path))
.then(() => cl.cloudgetFile('enrollments.STUDENTS.DM1578VT152.1480494800007.csv', 'test', path))
.then(() => cl.cloudgetFile('enrollments.STUDENTS.DM1578VT152.1480494800008.csv', 'test', path))
.then(() => cl.cloudgetFile('enrollments.STUDENTS.DM1578VT152.1480494800009.csv', 'test', path))
.then(() => cl.cloudgetFile('enrollments.STUDENTS.DM1578VT152.1480494800010.csv', 'test', path))
.then(() => log.info('\n (5) Passed........\n'))
.then(() => cl.cloudGetFilesBeforeDate(new Date(), 'test', 3, path1))
.then(() => log.info('\n (5.1) Passed........\n'))
.then(() => cl.cloudDeleteFilesBeforeDate(new Date(), 'test', 3))
.then(() => cl.cloudListFile('test'))
.then(() => cl.cloudListFile('test'))
.then(() => log.info('\n (6) Passed........\n'))
.then(() => log.info('\nCopy a file to Azure...'))
.then(() => cl.cloudStoreFile('./AZURETEST/enrollments.STUDENTS.DM1578VT152.1480494800005.csv', 'test'))
.then(() => cl.cloudListFile('test'))
.then(() => log.info('\n (7) Passed........\n'))
.then(() => cl.cloudDelFile('./AZURETEST/enrollments.STUDENTS.DM1578VT152.1480494800005.csv', 'test', 3))
.then(() => cl.cloudListFile('test'))
.then(() => log.info('\n (8) Passed........\n'))
.then(() => log.info('\n creating document database test,collection testcol\n'))
.then(() => cl.cloudGetDatabase('test'))
.then(() => log.info('Database connected successfully: '))
.then(() => cl.cloudGetCollection('test', 'testcol'))
.then(() => log.info('Collection connected successfully: '))
.then(() => log.info('\n (9) Passed........\n'))
.then(() => Promise.resolve(true))
.catch(error => log.info(error))
}

_test('./AZURETEST/', './REPLAY/')
.then(status => {
  if (status === true) {
    log.info('TEST IS OK')
  } else {
    console.error('TEST IS NOT OK,FAILED')
  }
})

module.exports = {test: _test}
